### ISSUE TITLE
Help test and translate InputStream Helper v0.4.4

### ISSUE THREAD

**Issue by mediaminister** [emilsvennesson/script.module.inputstreamhelper#256]
We would like to have the help of past and new testers/translators to get InputStream Helper tested and translated to the existing (and potentially) new languages. Here is an overview of the existing languages:

READY:

- [x] **English** *en_gb* -- translation complete
- [x] **Dutch** *nl_nl* -- translation complete @dagwieers @mediaminister, @basrieter, @dnicolaas
- [x] **German** *de_de* -- translation complete @flubshi, @horstle, @asciidisco
- [x] **French** *fr_fr* -- translation complete @brunoduc
- [x] **Hungarian** *hu_hu* -- translation complete @frodo19
- [x] **Russian** *ru_ru* -- translation complete @vlmaksime
- [x] **Swedish** *sv_se* -- translation complete @emilsvennesson @Sopor
- [x] **Croatian** *hr_hr* -- translation complete @arvvoid
- [x] **Italian** *it_it* -- translation complete @pinoelefante
- [x] **Greek** *el_gr* -- translation complete @Twilight0, @paraskevasleivadaros

TO DO:

- [ ] **Japanese** *ja_jp* -- #30821 and #30915 untranslated @Thunderbird2086
- [ ] **Korean** *kr_kr* -- #30821 and #30915 untranslated @Thunderbird2086

Please translate the untranslated strings.

**Comment by vlmaksime** [comment]
I'm got error, when trying (Re)install module. Here is the [logs](paste.kodi.tv/ipajoyenox)

**Comment by mediaminister** [comment]
Thanks already to all contributors for updating the translations.

There are still some untranslated strings for a couple of languages:

- [ ] **Greek** *el_gr* -- #30821 untranslated  @Twilight0, @paraskevasleivadaros
- [ ] **Japanese** *ja_jp* -- #30821 and #30915 untranslated @Thunderbird2086
- [ ] **Korean** *kr_kr* -- #30821 and #30915 untranslated @Thunderbird2086

**Comment by mediaminister** [comment]
I won't wait for missing translations any longer. v0.4.4 will be released this weekend.

**Comment by dagwieers** [comment]
We have created translator-teams in the @add-ons organization at: https://github.com/orgs/add-ons/teams/translators

This will help us translate Kodi add-ons to more languages in the future using less effort.
If you are willing to help out, join a language team!
